In [14]:
import numpy as np

STUDENT_NAME = "Jhon Martin Duat"
STUDENT_ID = 250204

np.random.seed(STUDENT_ID)
data = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
print(f"{STUDENT_NAME}'s Array:", data)

mean_val = np.mean(data)
std_val = np.std(data)
print("Mean:", mean_val, "Std Dev:", std_val)

Jhon Martin Duat's Array: [28 27 33 10 37  6 26 24 22 44]
Mean: 25.7 Std Dev: 10.835589508651571


In [15]:
import numpy as np

STUDENT_NAME = "Jhon Martin Duat"
STUDENT_ID = 250204

np.random.seed(STUDENT_ID)
matrix = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))
print(f"{STUDENT_NAME}'s Matrix:\n", matrix)

row_sums = np.sum(matrix, axis=1)
col_sums = np.sum(matrix, axis=0)
print("Row sums:", row_sums)
print("Column sums:", col_sums)

Jhon Martin Duat's Matrix:
 [[23  1 10  5]
 [ 6 22 12 16]
 [17  5 21 17]]
Row sums: [39 56 60]
Column sums: [46 28 43 38]


In [16]:
import numpy as np

STUDENT_NAME = "Jhon Martin Duat"
STUDENT_ID = 250204

np.random.seed(STUDENT_ID)
arr3d = np.random.randint(0, STUDENT_ID % 20 + 10, size=(3,3,3))
print(f"{STUDENT_NAME}'s 3D Array:\n", arr3d)

slice_mid = arr3d[:,1,:]
print("Slice[:,1,:]:\n", slice_mid)

Jhon Martin Duat's 3D Array:
 [[[ 6 11 12]
  [10  0  9]
  [ 4  5  9]]

 [[ 7  5 11]
  [ 0  4  4]
  [ 0  9  8]]

 [[ 4 11 12]
  [ 0  7 13]
  [ 2 10  3]]]
Slice[:,1,:]:
 [[10  0  9]
 [ 0  4  4]
 [ 0  7 13]]


In [17]:
import numpy as np

STUDENT_NAME = "Jhon Martin Duat"
STUDENT_ID = 250204

np.random.seed(STUDENT_ID)
x = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)

filtered = x[(x > STUDENT_ID % 50) & (x < STUDENT_ID % 100)]

print(f"{STUDENT_NAME}'s Original:", x)
print("Filtered subset:", filtered)

Jhon Martin Duat's Original: [28 27 33 10 37  6 26 24 22 44]
Filtered subset: []


In [18]:
import numpy as np

STUDENT_NAME = "Jhon Martin Duat"
STUDENT_ID = 250204

np.random.seed(STUDENT_ID)
A = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))
B = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))

print("Matrix A:\n", A)
print("Matrix B:\n", B)

product = A @ B
det_A = np.linalg.det(A)

print("A @ B:\n", product)
print("Determinant of A:", det_A)

Matrix A:
 [[23  1]
 [10  5]]
Matrix B:
 [[ 6 22]
 [12 16]]
A @ B:
 [[150 522]
 [120 300]]
Determinant of A: 104.99999999999997


In [19]:
import numpy as np

STUDENT_NAME = "Jhon Martin Duat"
STUDENT_ID = 250204

angles = np.linspace(0, 2*np.pi, 8)
sine_vals = np.sin(angles)
cos_vals = np.cos(angles)

print(f"{STUDENT_NAME}'s Angles:", angles)
print("Sine:", sine_vals)
print("Cosine:", cos_vals)

Jhon Martin Duat's Angles: [0.         0.8975979  1.7951958  2.6927937  3.5903916  4.48798951
 5.38558741 6.28318531]
Sine: [ 0.00000000e+00  7.81831482e-01  9.74927912e-01  4.33883739e-01
 -4.33883739e-01 -9.74927912e-01 -7.81831482e-01 -2.44929360e-16]
Cosine: [ 1.          0.6234898  -0.22252093 -0.90096887 -0.90096887 -0.22252093
  0.6234898   1.        ]


In [20]:
import numpy as np

STUDENT_NAME = "Jhon Martin Duat"
STUDENT_ID = 250204

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(4,4))

arr[::2, ::2] = 0

print(f"{STUDENT_NAME}'s Modified 4x4 Array:\n", arr)

Jhon Martin Duat's Modified 4x4 Array:
 [[ 0  1  0  5]
 [ 6 22 12 16]
 [ 0  5  0 17]
 [10  5 13  1]]


In [21]:
import numpy as np

STUDENT_NAME = "Jhon Martin Duat"
STUDENT_ID = 250204

np.random.seed(STUDENT_ID)
scores = np.random.randint(0, STUDENT_ID % 100 + 50, 10)

grades = np.where(scores >= STUDENT_ID % 70, 'Pass', 'Fail')

print(f"{STUDENT_NAME}'s Scores:", scores)
print("Grades:", grades)

Jhon Martin Duat's Scores: [27 26 32  9 36  5 25 23 21 43]
Grades: ['Pass' 'Pass' 'Pass' 'Fail' 'Pass' 'Fail' 'Pass' 'Fail' 'Fail' 'Pass']


In [22]:
import numpy as np

STUDENT_NAME = "Jhon Martin Duat"
STUDENT_ID = 250204

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))

flat_arr = arr.flatten()
transposed_arr = arr.T

print("Original array:\n", arr)
print("Flattened:", flat_arr)
print("Transposed:\n", transposed_arr)

Original array:
 [[23  1 10  5]
 [ 6 22 12 16]
 [17  5 21 17]]
Flattened: [23  1 10  5  6 22 12 16 17  5 21 17]
Transposed:
 [[23  6 17]
 [ 1 22  5]
 [10 12 21]
 [ 5 16 17]]


In [23]:
import numpy as np

STUDENT_NAME = "Jhon Martin Duat"
STUDENT_ID = 250204

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, (3,3))

mask = arr % 2 == 0
arr[mask] = -1

print("Array with conditional replacements:\n", arr)

Array with conditional replacements:
 [[23  1 -1]
 [ 5 -1 -1]
 [-1 -1 17]]


In [24]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Jhon Martin Duat"
STUDENT_ID = 250204

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    'Name': [STUDENT_NAME]*5,
    'Score': np.random.randint(STUDENT_ID % 50, STUDENT_ID % 100 + 50, 5),
    'YearsCodePro': np.random.randint(0, STUDENT_ID % 20 + 10, 5)
})

print(df)

               Name  Score  YearsCodePro
0  Jhon Martin Duat     31             5
1  Jhon Martin Duat     30             9
2  Jhon Martin Duat     36             7
3  Jhon Martin Duat     13             5
4  Jhon Martin Duat     40            11


In [25]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Jhon Martin Duat"
STUDENT_ID = 250204

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    'EdLevel': ['Bachelor','Master','PhD','Bachelor','Master'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

avg_salary = df.groupby('EdLevel')['ConvertedComp'].mean()

print(avg_salary)

EdLevel
Bachelor    83659.0
Master      75954.0
PhD         97434.0
Name: ConvertedComp, dtype: float64


In [26]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Jhon Martin Duat"
STUDENT_ID = 250204

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    'Country': ['Philippines','USA','UK','Canada','Germany'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

top5 = df.sort_values(by='ConvertedComp', ascending=False)
print(top5)

       Country  ConvertedComp
2           UK          97434
3       Canada          92064
1          USA          86747
0  Philippines          75254
4      Germany          65161


In [27]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Jhon Martin Duat"
STUDENT_ID = 250204

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    'Name':[STUDENT_NAME]*5,
    'YearsCodePro': np.random.randint(0, STUDENT_ID % 20 + 10, 5)
})

high_exp = df[df['YearsCodePro'] > STUDENT_ID % 10]
print(high_exp)

               Name  YearsCodePro
0  Jhon Martin Duat             6
1  Jhon Martin Duat            11
2  Jhon Martin Duat            12
3  Jhon Martin Duat            10


In [28]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Jhon Martin Duat"
STUDENT_ID = 250204

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

bins = [0, 50000, 100000, 150000, 200000]
labels = ['0-50k', '50-100k', '100-150k', '>150k']

df['Bracket'] = pd.cut(df['ConvertedComp'], bins=bins, labels=labels)
print(df)

   ConvertedComp  Bracket
0          75254  50-100k
1          86747  50-100k
2          97434  50-100k
3          92064  50-100k
4          65161  50-100k


In [29]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Jhon Martin Duat"
STUDENT_ID = 250204

np.random.seed(STUDENT_ID)

df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 150000, 5)})

df['LogComp'] = np.log(df['ConvertedComp'])
print(df)

   ConvertedComp    LogComp
0          75254  11.228624
1          86747  11.370751
2          97434  11.486931
3          92064  11.430239
4          65161  11.084616


In [30]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Jhon Martin Duat"
STUDENT_ID = 250204

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    'YearsCodePro': np.random.randint(0, STUDENT_ID % 20 + 10, 5),
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

corr_matrix = df.corr()
print(corr_matrix)

               YearsCodePro  ConvertedComp
YearsCodePro       1.000000       0.161311
ConvertedComp      0.161311       1.000000


In [31]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Jhon Martin Duat"
STUDENT_ID = 250204

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    'EdLevel':['Bachelor','Master','PhD','Bachelor','Master'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

summary = df.groupby('EdLevel')['ConvertedComp'].agg(['mean','median','std']).reset_index()
print(summary)

    EdLevel     mean   median           std
0  Bachelor  83659.0  83659.0  11886.464992
1    Master  75954.0  75954.0  15263.606979
2       PhD  97434.0  97434.0           NaN


In [32]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Jhon Martin Duat"
STUDENT_ID = 250204

np.random.seed(STUDENT_ID)

df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 150000, 5)})

threshold = 110000
df['HighPay'] = np.where(df['ConvertedComp'] > threshold, 'Yes', 'No')

print(df)

   ConvertedComp HighPay
0          75254      No
1          86747      No
2          97434      No
3          92064      No
4          65161      No


In [33]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Jhon Martin Duat"
STUDENT_ID = 250204

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    'Country': ['Philippines','USA','UK','Canada','Germany'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

top_countries = df.groupby('Country')['ConvertedComp'].agg(['mean','max'])
print(top_countries)

                mean    max
Country                    
Canada       92064.0  92064
Germany      65161.0  65161
Philippines  75254.0  75254
UK           97434.0  97434
USA          86747.0  86747
