In [1]:
import numpy as np

years_exp = np.array([1, 3, 5, 7, 10])
print("Years of Experience:", years_exp)

salaries = np.array([[50, 60, 70], [80, 90, 100]])
print("Salary Matrix:\n", salaries)

zeros_array = np.zeros((2, 2))
ones_array = np.ones((2, 3))
print("Zeros Array:\n", zeros_array)
print("Ones Array:\n", ones_array)

Years of Experience: [ 1  3  5  7 10]
Salary Matrix:
 [[ 50  60  70]
 [ 80  90 100]]
Zeros Array:
 [[0. 0.]
 [0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [2]:
exp_plus_5 = years_exp + 5
print("Years + 5:", exp_plus_5)

exp_times_2 = years_exp * 2
print("Years * 2:", exp_times_2)

sample1 = np.array([1, 2, 3])
sample2 = np.array([4, 5, 6])
dot_result = np.dot(sample1, sample2)
print("Dot Product:", dot_result)

Years + 5: [ 6  8 10 12 15]
Years * 2: [ 2  6 10 14 20]
Dot Product: 32


In [3]:
print("First year of experience:", years_exp[0])

print("First two salaries:", salaries[0, :2])

print("Second column salaries:", salaries[:, 1])

print("Last year of experience:", years_exp[-1])

First year of experience: 1
First two salaries: [50 60]
Second column salaries: [60 90]
Last year of experience: 10


In [4]:
reshaped_exp = np.reshape(np.arange(1, 7), (2, 3))
print("Reshaped Experience Array:\n", reshaped_exp)

flattened_exp = reshaped_exp.flatten()
print("Flattened Array:", flattened_exp)

print("Transposed Array:\n", reshaped_exp.T)

Reshaped Experience Array:
 [[1 2 3]
 [4 5 6]]
Flattened Array: [1 2 3 4 5 6]
Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]


In [5]:
bonus = np.array([5, 10, 15])
salaries_with_bonus = salaries + bonus
print("Salaries after bonus:\n", salaries_with_bonus)

Salaries after bonus:
 [[ 55  70  85]
 [ 85 100 115]]


In [6]:
print("Mean experience:", np.mean(years_exp))

print("Std deviation of experience:", np.std(years_exp))

print("Max salary:", np.max(salaries), "Min salary:", np.min(salaries))

print("Sum of all salaries:", np.sum(salaries))

Mean experience: 5.2
Std deviation of experience: 3.1240998703626617
Max salary: 100 Min salary: 50
Sum of all salaries: 450


In [7]:
angles = np.array([0, np.pi/4, np.pi/2])
print("Sine of angles:", np.sin(angles))
print("Cosine of angles:", np.cos(angles))

salary_sums = np.apply_along_axis(np.sum, 1, salaries)
print("Sum of Salaries per person:", salary_sums)

Sine of angles: [0.         0.70710678 1.        ]
Cosine of angles: [1.00000000e+00 7.07106781e-01 6.12323400e-17]
Sum of Salaries per person: [180 270]


In [8]:
import pandas as pd

data = np.random.randint(1, 50, size=(5, 3))

df_data = pd.DataFrame(data, columns=['X', 'Y', 'Z'])
print("Generated Data:\n", df_data)

df_data['Log_X'] = np.log(df_data['X'])
df_data['Sqrt_Y'] = np.sqrt(df_data['Y'])
print("DataFrame with NumPy Transformations:\n", df_data)

print("Correlation Matrix:\n", df_data.corr())

Generated Data:
     X   Y   Z
0  39  16  42
1  39  46  24
2  41  30  38
3  38   9  14
4  14  13  41
DataFrame with NumPy Transformations:
     X   Y   Z     Log_X    Sqrt_Y
0  39  16  42  3.663562  4.000000
1  39  46  24  3.663562  6.782330
2  41  30  38  3.713572  5.477226
3  38   9  14  3.637586  3.000000
4  14  13  41  2.639057  3.605551
Correlation Matrix:
                X         Y         Z     Log_X    Sqrt_Y
X       1.000000  0.396376 -0.358072  0.999332  0.395515
Y       0.396376  1.000000 -0.067196  0.383560  0.994971
Z      -0.358072 -0.067196  1.000000 -0.381057  0.021545
Log_X   0.999332  0.383560 -0.381057  1.000000  0.379771
Sqrt_Y  0.395515  0.994971  0.021545  0.379771  1.000000


In [9]:
df_data.to_csv('sample_data.csv', index=False)
print("Data saved to 'sample_data.csv'.")

df_imported = pd.read_csv('sample_data.csv')
print("Imported DataFrame:\n", df_imported)

summary_stats = df_imported.describe()
print("Summary Statistics:\n", summary_stats)

print("Column Means:\n", df_imported.mean())
print("Column Standard Deviations:\n", df_imported.std())

Data saved to 'sample_data.csv'.
Imported DataFrame:
     X   Y   Z     Log_X    Sqrt_Y
0  39  16  42  3.663562  4.000000
1  39  46  24  3.663562  6.782330
2  41  30  38  3.713572  5.477226
3  38   9  14  3.637586  3.000000
4  14  13  41  2.639057  3.605551
Summary Statistics:
                X          Y          Z     Log_X    Sqrt_Y
count   5.000000   5.000000   5.000000  5.000000  5.000000
mean   34.200000  22.800000  31.800000  3.463468  4.573021
std    11.344602  15.188812  12.296341  0.461681  1.536016
min    14.000000   9.000000  14.000000  2.639057  3.000000
25%    38.000000  13.000000  24.000000  3.637586  3.605551
50%    39.000000  16.000000  38.000000  3.663562  4.000000
75%    39.000000  30.000000  41.000000  3.663562  5.477226
max    41.000000  46.000000  42.000000  3.713572  6.782330
Column Means:
 X         34.200000
Y         22.800000
Z         31.800000
Log_X      3.463468
Sqrt_Y     4.573021
dtype: float64
Column Standard Deviations:
 X         11.344602
Y         1

In [15]:
import pandas as pd
import numpy as np

df_kaggle = pd.read_csv('survey_results_public.csv')
print("Loaded Dataset:\n", df_kaggle.head())

df_subset = df_kaggle[['Country', 'EdLevel', 'YearsCodePro', 'ConvertedCompYearly']]
print("Subset of Data:\n", df_subset.head())

df_clean = df_subset.dropna()
print("Cleaned Data:\n", df_clean.head())

df_clean['YearsCodePro'] = df_clean['YearsCodePro'].replace({
    'Less than 1 year': 0,
    'More than 50 years': 50
})

df_clean['YearsCodePro'] = pd.to_numeric(df_clean['YearsCodePro'], errors='coerce')

df_clean['ExperienceLevel'] = np.where(df_clean['YearsCodePro'] >= 10, 'Senior', 'Junior')

grouped_data = df_clean.groupby(['Country', 'ExperienceLevel'])['ConvertedCompYearly'].mean()
print("Grouped Average Salary:\n", grouped_data.head())

grouped_data = grouped_data.reset_index()
print("Formatted Grouped Data:\n", grouped_data.head())

Loaded Dataset:
    ResponseId     Q120                      MainBranch              Age  \
0           1  I agree                   None of these  18-24 years old   
1           2  I agree  I am a developer by profession  25-34 years old   
2           3  I agree  I am a developer by profession  45-54 years old   
3           4  I agree  I am a developer by profession  25-34 years old   
4           5  I agree  I am a developer by profession  25-34 years old   

                                          Employment  \
0                                                NaN   
1                                Employed, full-time   
2                                Employed, full-time   
3                                Employed, full-time   
4  Employed, full-time;Independent contractor, fr...   

                             RemoteWork  \
0                                   NaN   
1                                Remote   
2  Hybrid (some remote, some in-person)   
3  Hybrid (some remote,